site_name: emacs.d

docs_dir: docs_src
site_dir: site

plugins:
  - search
  - awesome-nav
  - git-revision-date-localized

theme:
  name: terminal
  palette: gruvbox_dark
  # name: bootstrap386
  # name: material

markdown_extensions:
  # TOC settings
  - toc:
      baselevel: "3"
      toc_depth: "3"

  # Code highlighting
  # - codehilite:
  #     guess_lang: false

  # # Admonitions (note boxes)
  # - admonition

  # # Fenced code blocks
  # - fenced_code

  # # Tables
  # - tables

  # # Footnotes
  # - footnotes

  # # Abbreviations
  # - abbr

  # # Definition lists
  # - def_list

  - pymdownx.superfences         # required extension
  - pymdownx.highlight:
      use_pygments: true         # use pygments library    
      pygments_style: lightbulb    # use 'default' style
      noclasses: true            # update HTML style attr
  - pymdownx.inlinehilite        # style inline code
